#!/bin/bash
rm /home/michael/stock_project/stock_cache.txt
python3 /home/michael/stock_project/user_interaction.py
Rscript /home/michael/stock_project/stock_plotter.R
eog /home/michael/stock_project/stock_plot.png
