#!/bin/bash
rm /home/michael/stock_project/stock_cache.txt
python3 /home/michael/stock_project/user_interaction.py > stock_cache.txt
R script /home/michael/stock_project/stock_plotter.R
eog stock_plot.png
